---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
  - name: hello_hapi_source
    type: git
    source: &repo-source
      uri: https://github.com/SjurWarEagle/deploy-info
      branch: master
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: Install dependencies
    plan:
      - get: hello_hapi_source
        trigger: true
      - get: dependency-cache
  - name: Run tests
    plan:
      - get: hello_hapi_source
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      - task: run the test suite
        file: hello_hapi_source/concourse/run_test.yml
