---
resources:
  - name: every-5min
    type: time
    icon: clock-outline
    source: {interval: 5m}
  - name: deploy-info-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/SjurWarEagle/deploy-info
  - name: nodejs.org-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/nodejs/nodejs.org.git
#  - name: inTheMorning
#    icon: alarm
#    type: time
#    source:
#      start: 0:00 AM
#      stop:  0:05 AM
#      location: Europe/Berlin

jobs:
  - name: test
    public: true
    plan:
      - get: every-5min
        trigger: true
      - get: nodejs.org-git
        trigger: true
#      - get: inTheMorning
#        trigger: false
      - get: deploy-info-git
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: "12" }
          inputs:
            - name: nodejs.org-git
          run:
            path: /bin/sh
            args:
              - -c
              - |
                export GITHUB_USER=((GITHUB_USER))
                export GITHUB_TOKEN=((GITHUB_TOKEN))
                git clone https://github.com/SjurWarEagle/deploy-info
                cd deploy-info
                curl ((GIST_URL)) > src/config/config.ts
                node --version
                npm install
                npm run start
